#ifndef ALUTINTERFACERULE_H
#define ALUTINTERFACERULE_H

#include "ainterfacerule.h"
#include "alutsurfacedata.h"

#include <QString>

// Interface rule using surface look-up tables generated by ray tracing over a measured
// 3D surface topography (approach of Roncali & Cherry 2013, Phys.Med.Biol. 58:2185).
// Multiple micro-reflections, shadowing and masking are contained in the LUT itself,
// so the rule does not use (and cannot have) the microfacet "rough surface" add-on.
// The LUT is direction-specific: n1(from) -> n2(to) is baked in at generation time,
// therefore the "Symmetric" option is not supported.

class ALutInterfaceRule : public AInterfaceRule
{
public:
    ALutInterfaceRule(int MatFrom, int MatTo);

    EInterfaceRuleResult calculate(APhoton * Photon, const double * NormalVector) override;

    QString getType() const override         {return "DavisLUT";}
    QString getAbbreviation() const override {return "LUT";}
    QString getReportLine() const override;
    QString getLongReportLine() const override;
    QString getDescription() const override;

    void initializeWaveResolved() override;

    bool canHaveRoughSurface() const override {return false;}
    bool canBeSymmetric() const override      {return false;}

    QString loadLUT(const QString & fileName);

    // non-blocking check that the LUT metadata n1/n2 agree with the refractive indices
    // of the materials this rule is assigned to; returns empty string if consistent
    QString getMaterialConsistencyWarning() const;

    ALutSurfaceData Data;
    QString LutFileName;   // file the LUT was loaded from (for reports only, data are embedded)

protected:
    void doWriteToJson(QJsonObject & json) const override;
    bool doReadFromJson(const QJsonObject & json) override;

    QString doCheckOverrideData() override;
};

#endif // ALUTINTERFACERULE_H
